In [487]:
# Import packages
import numpy as np
curDay = 25

# Download input file
from download_inputs import download_inputs

download_inputs(curDay)

200


In [488]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'
# curIn = np.loadtxt(filename)

inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [489]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}test.txt'

inputFileTest = open(filenameTest)
inputsTest = []
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input') 

Done loading test-input


In [490]:
curInput = inputsTest 
curInput = inputs

In [684]:
def SnafuToDecimal(curSn):
    # Make empty array 
    toAdd = np.zeros((len(curSn),))

    for i in range(len(curSn)):
        
        curSym = curSn[i]
        
        if curSym == '0':
            toAdd[i] = 0
        elif curSym == '1':
            toAdd[i] = 1
        elif curSym == '2':
            toAdd[i] = 2
        elif curSym == '-':
            toAdd[i] = -1
        elif curSym == '=':
            toAdd[i] = -2

    deciMult = np.power(5,np.arange(len(curSn)-1,-1,-1),dtype='int64')
    return np.sum(toAdd * deciMult,dtype='int64')
    # deciMult = np.power(5,np.arange(len(curSn)-1,-1,-1))
    # return np.sum(toAdd * deciMult)


In [686]:
curSum = 0
for curL in curInput:
    curSum += SnafuToDecimal(curL)
    # print(SnafuToDecimal(curL))
print('Current sum:',curSum)

Current sum: 31487399529835


In [688]:
# decimalToSnafu(curSum)

In [694]:

# deciMultFull = np.power(5,np.arange(13,-1,-1))
# deciMultFull 
# deciMultFull = np.power(5,np.arange(20,-1,-1),dtype='int64')

# deciMultFull 

In [692]:
# curSum - deciMultFull
# 13426377694 - deciMultFull

In [656]:
# decimalToSnafu(13426377694)
# decimalToSnafu(7322862069)

In [693]:
# # SnafuToDecimal('2211000-2==1-2=--')

# deciMultFull = np.power(5,np.arange(25,-1,-1),dtype='int64')
# deciMultFull

In [695]:
# curDe = 23
# curDeciMult = deciMultFull[deciMultFull < curDe]

def decimalToSnafu(curDe):
    
    # deciMultFull = np.power(5,np.arange(13,-1,-1))
    deciMultFull = np.power(5,np.arange(25,-1,-1),dtype='int64')
    maxIndexToUse = (curDe/deciMultFull > 0.5)
    # for i in deciMultFull:
    #     print(curDe/i)
    # print(curDe/deciMultFull)
    # print(maxIndexToUse)

    curMult = deciMultFull[maxIndexToUse]
    # curMult = deciMultFull 

    toReturn = ''
    remi = curDe 
    for p in range(0,len(curMult)):
        
        # print(curMult)
        toAdd = ''
        # curNum = remi.astype('longlong')/curMult[p]
        curNum = remi/curMult[p]
        
        # print(type(curNum))
        # print('remi',remi,'curNum:',curNum)
        # if (curNum == 0):
        #     toAdd = '0'
        if (curNum >= 0.5):

            if (curNum >= 0.5):
                toAdd = '1'
                remi -= curMult[p]        
            curNum = remi/curMult[p]
            if (curNum  >= 0.5):
                toAdd = '2'
                remi -= curMult[p]
        elif (curNum <= -0.5):      
            
            # curNum = remi/curMult[p]
            if (curNum <= -0.5):
                toAdd = '-'
                remi += curMult[p]   
            curNum = remi/curMult[p]
            if (curNum <= -0.5):
                toAdd = '='
                remi += curMult[p]
        else:
            toAdd = '0'
            # print('asfd')

        # print('ToAdd:',toAdd)
        toReturn += toAdd 

    return toReturn

# # decimalToSnafu(5)
# for i in range(0,50,5):
#     print(f'{i}:',decimalToSnafu(i))
# curDe = np.power(5,13).astype('longlong') 
# curDe = np.power(5,14)
# type(curDe)
p2 = decimalToSnafu(curSum)
print('Part 2:',p2)

Part 2: 2=112--220-=-00=-=20


In [696]:
# deciMultFull

In [643]:
# '1' 
curSum - 30517578125 - 6103515625*2

1219346444

In [646]:
decimalToSnafu(13426377694)
decimalToSnafu(1219346444)
# np.log10(curSum)


'00000001000-2==1-2=--'

In [628]:
# decimalToSnafu(curSum)
print(curSum)
curVec = np.zeros(deciMultFull.shape,dtype='long')
curVec[-6] = 1
print(curVec)
np.sum(curVec * deciMultFull)
# ((30517578125) +  (6103515625*2))

43943955819
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


3125

In [177]:
SnafuToDecimal('1==')

13

In [213]:
# print(curInput[0])
# print(SnafuToDecimal())
# print(curInput[0])
curDe = 1747 
curDe = 13
# Idea: Simply reversing?

deciMultFull = np.power(5,np.arange(13,-1,-1))
curDeciMult = deciMultFull[deciMultFull < curDe]

# curDe / deciMultFull[-5:]

# lastNeededFactor = np.where((curDe / deciMultFull) <= 2)[-1][-1]
# deciMultFull[lastNeededFactor:]

# curDeciMult
# np.power(curDe,1/2)
# deciMultFull = np.power(5,1/np.arange(15,-1,-1))
# np.power(5,1/np.arange(5,0,-1))
# print((deciMultFull/5).astype(int) )
print(deciMultFull)
curDe = 12
print(curDe)
curDe / deciMultFull[10:]

[1220703125  244140625   48828125    9765625    1953125     390625
      78125      15625       3125        625        125         25
          5          1]
12


array([ 0.096,  0.48 ,  2.4  , 12.   ])

In [480]:
SnafuToDecimal('0100')
SnafuToDecimal('10=')
# SnafuToDecimal('100')

23

0: 
1: 1
2: 2
3: 1=
4: 1-
5: 10
6: 11
7: 12
8: 2=
9: 2-
10: 20
11: 21
12: 22
13: 1==
14: 1=-
15: 1=0
16: 1=1
17: 1=2
18: 1-=
19: 1--
20: 1-0
21: 1-1
22: 1-2
23: 10=
24: 10-
25: 100
26: 101
27: 102
28: 11=
29: 11-
30: 110
31: 111
32: 112
33: 12=
34: 12-
35: 120
36: 121
37: 122
38: 2==
39: 2=-
40: 2=0
41: 2=1
42: 2=2
43: 2-=
44: 2--
45: 2-0
46: 2-1
47: 2-2
48: 20=
49: 20-


In [342]:

curDe = 25
print('curDe',curDe)
maxIndexToUse = (curDe/deciMultFull > 0.5)
curMult = deciMultFull[maxIndexToUse]
curDe/curMult
numFactorsToUse = ((curDe/deciMultFull)/0.5).astype(int)
# numFactorsToUse[numFactorsToUse > 0] 
numFactorsToUse
toReturn = ''
remi = curDe 
for p in range(10,len(deciMultFull)):
    
    numFactorsToUse = ((remi/deciMultFull)/0.5).astype(int)
    print(numFactorsToUse[p:])
    # if numFactorsToUse[p] > 0:
    print(numFactorsToUse[p],deciMultFull[p])
    curAdd = ''
    if numFactorsToUse[p] == 0:
        curAdd = '0'
        # remi -= deciMultFull[p]
    if numFactorsToUse[p] >= 1:
        curAdd = '1'
        remi -= deciMultFull[p]
    if numFactorsToUse[p] >= 2:
        curAdd = '2'
        remi -= deciMultFull[p]
        
    if numFactorsToUse[p] <= -1:
        curAdd = '-'
        remi -= deciMultFull[p]
    if numFactorsToUse[p] <= -2:
        curAdd = '='
        remi -= deciMultFull[p]

    toReturn += curAdd 
    print('curadd',curAdd)
    print('Curreturn: ',toReturn)
    print('Remi:',remi)
toReturn

# remi = curDe 
# toReturn = ''
# thisMult = curMult[0]
# print(remi)
# countToAdd = 0
# while (remi/thisMult) > 1:
#     countToAdd += 1
#     remi -= thisMult 
# countToAdd
# print(remi)


curDe 25
[ 0  2 10 50]
0 125
curadd 0
Curreturn:  0
Remi: 25
[ 2 10 50]
2 25
curadd 2
Curreturn:  02
Remi: -25
[-10 -50]
-10 5
curadd =
Curreturn:  02=
Remi: -35
[-70]
-70 1
curadd =
Curreturn:  02==
Remi: -37


'02=='

In [369]:
remi = 13 
((remi/deciMultFull)/0.5).astype(int)
# deciMultFull

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  5, 26])

In [365]:
# remi = 24
# (remi/deciMultFull).astype(int)
# SnafuToDecimal('10-')

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4, 24])

In [229]:
# deciMultFull[:-1] - 2 *deciMultFull[1:]
# deciMultFull[:-1]*2 + deciMultFull[1:]*2
# SnafuToDecimal('1==')
SnafuToDecimal('100')

25

In [40]:
curSn = inputsTest[0]
curSn = '20'

print(curSn)
toAdd = np.zeros((len(curSn),))
toAdd


for i in range(len(curSn)):
    curSym = curSn[i]
    print(curSym)
    if curSym == '0':
        toAdd[i] = 0
    elif curSym == '1':
        toAdd[i] = 1
    elif curSym == '2':
        toAdd[i] = 2
    elif curSym == '-':
        toAdd[i] = -1
    elif curSym == '=':
        toAdd[i] = -2

print(toAdd)
deciMult = np.power(5,np.arange(len(curSn)-1,-1,-1))
np.sum(toAdd * deciMult)

20
2
0
[2. 0.]


10.0

In [38]:
np.power(5,np.arange(len(curSn)-1,-1,-1))

array([5, 1], dtype=int32)