In [1]:
# Import packages
import numpy as np
curDay = 20

# Download input file
from download_inputs import download_inputs

download_inputs(curDay)

200


In [2]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'
# curIn = np.loadtxt(filename)

inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [241]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}test.txt'

inputFileTest = open(filenameTest)
inputsTest = []
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input') 

Done loading test-input


In [523]:
curIn = np.array([4, 5, 6, 1, 7, 8, 9])
curIn = np.array([4, -2, 5, 6, 7, 8, 9])
curIn = np.loadtxt(filenameTest)
curIn = np.loadtxt(filename)

In [524]:
ar = curIn.copy()
curOrd = np.arange(len(ar))
curInd = 0
nextInd = curInd
curPos = np.where(curOrd == nextInd)[0][0]
oldPos = curOrd[curPos]

curInd = -1 

print(ar,curOrd)

for k in range(len(ar)):
    # print('--')
    # Get next
    nextInd = curInd + 1
    curPos = np.where(curOrd == nextInd)[0][0]
    curInd = nextInd

    # oldPos = curOrd[curInd]
    # oldPos = curInd  
    # oldPos = curOrd[curPos]
    oldPos = curPos 
    # print(ar,'Start, move',int(ar[oldPos]),curOrd)
    toMove = int(ar[oldPos]) 
    
    # print('Move',toMove)
    # print(ar)

    toMoveFixed = (oldPos + toMove) % (len(ar)-1) 

    ar = np.delete(ar,oldPos)
    ar = np.insert(ar,toMoveFixed,toMove)

    curOrd = np.delete(curOrd,oldPos)
    curOrd = np.insert(curOrd,toMoveFixed,curInd)

    if (toMoveFixed == 0):
        ar = np.roll(ar,-1)
        curOrd = np.roll(curOrd,-1)


    # print(ar,curOrd)
    # print(ar)

    # print('--')
    # # Get next
    # nextInd = curInd + 1
    # curPos = np.where(curOrd == nextInd)[0][0]
    # curInd = nextInd



[ 9688.   470. -3016. ...  4936.  8347.  3988.] [   0    1    2 ... 4997 4998 4999]


In [525]:
zeroPos = np.where(ar == 0)[0][0]

v1 = int(np.roll(ar,-zeroPos - 1000)[0])
v2 = int(np.roll(ar,-zeroPos - 2000)[0])
v3 = int(np.roll(ar,-zeroPos - 3000)[0])

p1 = v1+v2+v3 
p1 

9687

# Part 2

In [587]:
curIn = np.array([4, 5, 6, 1, 7, 8, 9])
curIn = np.array([4, -2, 5, 6, 7, 8, 9])
curIn = np.loadtxt(filenameTest)
curIn = np.loadtxt(filename)
encKey = 811589153

In [588]:
curIn * encKey
curIn

array([ 9688.,   470., -3016., ...,  4936.,  8347.,  3988.])

In [589]:
actVal = curIn * encKey 
modVal = actVal % len(curIn)

In [590]:
ar = curIn.copy()
ar = ar * encKey
curOrd = np.arange(len(ar))
curInd = 0
nextInd = curInd
curPos = np.where(curOrd == nextInd)[0][0]
oldPos = curOrd[curPos]

curInd = -1 

print(ar)

for i in range(10):
    curInd = -1
    for k in range(len(ar)):
        # print('--')
        # Get next
        nextInd = curInd + 1
        curPos = np.where(curOrd == nextInd)[0][0]
        curInd = nextInd

        # oldPos = curOrd[curInd]
        # oldPos = curInd  
        # oldPos = curOrd[curPos]
        oldPos = curPos 
        # print(ar,'Start, move',int(ar[oldPos]),curOrd)
        toMove = int(ar[oldPos]) 
        
        # print('Move',toMove)
        # print(ar)

        toMoveFixed = (oldPos + toMove) % (len(ar)-1) 
        # print(toMove,toMoveFixed)

        ar = np.delete(ar,oldPos)
        ar = np.insert(ar,toMoveFixed,toMove)

        curOrd = np.delete(curOrd,oldPos)
        curOrd = np.insert(curOrd,toMoveFixed,curInd)

        if (toMoveFixed == 0):
            ar = np.roll(ar,-1)
            curOrd = np.roll(curOrd,-1)

    # print(ar.astype(int))
    print(np.roll(ar,1))

[ 7.86267571e+12  3.81446902e+11 -2.44775289e+12 ...  4.00600406e+12
  6.77433466e+12  3.23661754e+12]
[ 4.85086837e+12 -8.09803657e+12  4.18130732e+12 ... -8.76516285e+11
  3.43951483e+12  7.40169308e+11]
[-6.06338256e+12 -3.24635661e+10  6.01955675e+12 ... -7.82534261e+12
 -1.85448121e+12  5.10246100e+12]
[-6.76946513e+12  4.18130732e+12  2.63928793e+12 ... -7.24830273e+12
  1.49738199e+12 -4.06362689e+12]
[-1.42920850e+12 -5.63648667e+12 -3.48821018e+12 ...  7.80424130e+12
 -3.44844231e+12  7.37734540e+12]
[-1.38375951e+12 -4.52055158e+11  5.79718132e+12 ...  3.33644301e+12
 -5.47173407e+12  3.58803565e+12]
[ 7.43091028e+12 -4.31440794e+12 -1.54445416e+12 ...  8.61907680e+11
  4.54976879e+12 -6.48784369e+12]
[ 2.04033513e+12 -2.84786634e+12 -8.63530859e+11 ... -7.85212506e+12
 -6.25329442e+12 -5.97654252e+12]
[1.02503710e+12 4.58953666e+12 1.36915090e+12 ... 2.30491319e+12
 4.63904360e+12 6.31172884e+12]
[ 3.41516716e+12  9.33327526e+10  3.09053149e+12 ... -3.18629901e+12
 -3.320211

In [591]:
zeroPos = np.where(ar == 0)[0][0]

v1 = int(np.roll(ar,-zeroPos - 1000)[0])
v2 = int(np.roll(ar,-zeroPos - 2000)[0])
v3 = int(np.roll(ar,-zeroPos - 3000)[0])

p2 = v1+v2+v3 
p2

1338310513297

# Old below

In [571]:
ar = curIn.copy()
actVal = ar * encKey 
modVal = actVal % len(ar)
curOrd = np.arange(len(ar))

curInd = -1 
for k in range(len(ar)):
    # print('--')
    # Get next
    nextInd = curInd + 1
    curPos = np.where(curOrd == nextInd)[0][0]
    curInd = nextInd

    oldPos = curPos
    # print(actVal,'Start, move',int(modVal[oldPos]),curOrd)
    toMove = int(actVal[oldPos]) 
    
    # print('Move',toMove)
    # print(modVal)

    toMoveFixed = (oldPos + toMove) % (len(actVal)-1) 


    curOrd = np.delete(curOrd,oldPos)
    curOrd = np.insert(curOrd,toMoveFixed,curInd)
    
    actVal = np.delete(actVal,oldPos)
    actVal = np.insert(actVal,toMoveFixed,toMove)

    if (toMoveFixed == 0):
        actVal = np.roll(actVal,-1)
        curOrd = np.roll(curOrd,-1)


print(actVal.astype(int))

[-2147483648 -2147483648 -1623178306 -2147483648  1623178306   811589153
           0]


In [566]:
ar = curIn.copy()
actVal = ar * encKey 
modVal = actVal % len(ar)
curOrd = np.arange(len(ar))

curInd = -1 

print(ar,curOrd)

for i in range(10):
    curInd = -1 
    for k in range(len(ar)):
        # print('--')
        # Get next
        nextInd = curInd + 1
        curPos = np.where(curOrd == nextInd)[0][0]
        curInd = nextInd

        oldPos = curPos
        # print(actVal,'Start, move',int(modVal[oldPos]),curOrd)
        toMove = int(actVal[oldPos]) 
        
        # print('Move',toMove)
        # print(modVal)

        toMoveFixed = (oldPos + toMove) % (len(modVal)-1) 


        curOrd = np.delete(curOrd,oldPos)
        curOrd = np.insert(curOrd,toMoveFixed,curInd)
        
        actVal = np.delete(actVal,oldPos)
        actVal = np.insert(actVal,toMoveFixed,toMove)

        if (toMoveFixed == 0):
            modVal = np.roll(modVal,-1)
            curOrd = np.roll(curOrd,-1)


    print(actVal)

[ 1.  2. -3.  3. -2.  0.  4.] [0 1 2 3 4 5 6]
[ 0.00000000e+00 -2.43476746e+09 -1.62317831e+09  2.43476746e+09
  8.11589153e+08  1.62317831e+09  3.24635661e+09]
[ 0.00000000e+00  1.62317831e+09 -1.62317831e+09  8.11589153e+08
  2.43476746e+09 -2.43476746e+09  3.24635661e+09]
[ 0.00000000e+00 -1.62317831e+09  8.11589153e+08 -2.43476746e+09
  1.62317831e+09  2.43476746e+09  3.24635661e+09]
[-2.43476746e+09  0.00000000e+00  1.62317831e+09  8.11589153e+08
  2.43476746e+09 -1.62317831e+09  3.24635661e+09]
[ 2.43476746e+09  1.62317831e+09 -1.62317831e+09 -2.43476746e+09
  0.00000000e+00  8.11589153e+08  3.24635661e+09]
[ 2.43476746e+09  8.11589153e+08  3.24635661e+09 -1.62317831e+09
  0.00000000e+00  1.62317831e+09 -2.43476746e+09]
[-2.43476746e+09  2.43476746e+09  3.24635661e+09 -1.62317831e+09
  1.62317831e+09  0.00000000e+00  8.11589153e+08]
[-2.43476746e+09 -1.62317831e+09  3.24635661e+09  2.43476746e+09
  8.11589153e+08  1.62317831e+09  0.00000000e+00]
[ 2.43476746e+09 -1.62317831e+09  

In [555]:
ar = curIn.copy()
actVal = ar * encKey 
modVal = actVal % len(ar)
curOrd = np.arange(len(ar))

curInd = -1 

print(ar,curOrd)

for k in range(len(ar)):
    print('--')
    # Get next
    nextInd = curInd + 1
    curPos = np.where(curOrd == nextInd)[0][0]
    curInd = nextInd

    oldPos = curPos 
    # print(modVal,'Start, move',int(modVal[oldPos]),curOrd)
    print(modVal)
    print(actVal,'Start, move',int(modVal[oldPos]),curOrd)
    toMove = int(actVal[oldPos]) 
    
    # print('Move',toMove)
    # print(modVal)

    toMoveFixed = (oldPos + toMove) % (len(modVal)-1) 

    # modVal = np.delete(modVal,oldPos)
    # modVal = np.insert(modVal,toMoveFixed,toMove)
    
    modVal = np.delete(modVal,oldPos)
    modVal = np.insert(modVal,toMoveFixed,toMove)

    curOrd = np.delete(curOrd,oldPos)
    curOrd = np.insert(curOrd,toMoveFixed,curInd)
    
    actVal = np.delete(actVal,oldPos)
    actVal = np.insert(actVal,toMoveFixed,toMove)

    if (toMoveFixed == 0):
        modVal = np.roll(modVal,-1)
        curOrd = np.roll(curOrd,-1)




[ 1.  2. -3.  3. -2.  0.  4.] [0 1 2 3 4 5 6]
--
[4. 1. 2. 5. 6. 0. 2.]
[ 8.11589153e+08  1.62317831e+09 -2.43476746e+09  2.43476746e+09
 -1.62317831e+09  0.00000000e+00  3.24635661e+09] Start, move 4 [0 1 2 3 4 5 6]
--
[1.00000000e+00 2.00000000e+00 5.00000000e+00 6.00000000e+00
 0.00000000e+00 8.11589153e+08 2.00000000e+00]
[ 1.62317831e+09 -2.43476746e+09  2.43476746e+09 -1.62317831e+09
  0.00000000e+00  8.11589153e+08  3.24635661e+09] Start, move 1 [1 2 3 4 5 0 6]
--
[2.00000000e+00 5.00000000e+00 6.00000000e+00 0.00000000e+00
 1.62317831e+09 8.11589153e+08 2.00000000e+00]
[-2.43476746e+09  2.43476746e+09 -1.62317831e+09  0.00000000e+00
  1.62317831e+09  8.11589153e+08  3.24635661e+09] Start, move 2 [2 3 4 5 1 0 6]
--
[ 5.00000000e+00  6.00000000e+00  0.00000000e+00 -2.43476746e+09
  1.62317831e+09  8.11589153e+08  2.00000000e+00]
[ 2.43476746e+09 -1.62317831e+09  0.00000000e+00 -2.43476746e+09
  1.62317831e+09  8.11589153e+08  3.24635661e+09] Start, move 5 [3 4 5 2 1 0 6]
--
[ 6.0

# Old below

In [476]:
## WORKING!

ar = curIn.copy()
od = np.arange(len(ar))
curInd = 0
oldPos = od[curInd]

print(ar,'Start, move',int(ar[oldPos]),od)
toMove = int(ar[oldPos]) 

toMoveFixed = (oldPos + toMove) % (len(ar)-1) 

ar = np.delete(ar,oldPos)
ar = np.insert(ar,toMoveFixed,toMove)

od = np.delete(od,oldPos)
od = np.insert(od,toMoveFixed,curInd)



print(ar,od)

[ 1.  2. -3.  3. -2.  0.  4.] Start, move 1 [0 1 2 3 4 5 6]
[ 2.  1. -3.  3. -2.  0.  4.] [1 0 2 3 4 5 6]


In [454]:
ar = curIn.copy()
oldPos = 0

print(ar,'Start, move',int(ar[oldPos]))
curVal = int(ar[oldPos]) 
# curVal = 99
toMove = curVal 


if toMove > 0:
    toMoveFixed = (oldPos + toMove) % (len(ar)-1) 
else:
    toMoveFixed = (oldPos + toMove) % (len(ar)-1)

ar = np.delete(ar,oldPos)

ar = np.insert(ar,toMoveFixed,curVal)
# print(ar,'insert')




[ 4 -2  5  6  7  8  9] Start, move 4


In [395]:
# Working solution, but the number should be popped before moving, otherwise it will be in the way for itself (and x > len(ar) will be one to small)
ar = curIn.copy()
oldPos = 4

print(ar,'Start')
toMove = int(ar[oldPos])

if toMove > 0:
    toMoveFixed = (oldPos + toMove + 1) % len(ar)
else:
    toMoveFixed = (oldPos + toMove) % len(ar)

ar = np.insert(ar,toMoveFixed,toMove)
print(ar,'insert')

if (toMoveFixed < oldPos):
    ar = np.delete(ar,oldPos+1)
    print(ar,'Delete')
else:
    ar = np.delete(ar,oldPos)
    print(ar,'Delete')

[ 4 -2  5  6  7  8  9] Start
[ 4 -2  5  6  7  7  8  9] insert
[ 4 -2  5  6  7  8  9] Delete


In [394]:
ar = curIn.copy()
oldPos = 3
toMove = int(ar[oldPos])
print(ar,'Start, move',toMove)

# if toMove > 0:
#     toMoveFixed = (oldPos + toMove + 1) % len(ar)
# else:
#     toMoveFixed = (oldPos + toMove) % len(ar) 
if toMove > 0:
    toMoveFixed = (toMove + 1) % len(ar)
else:
    toMoveFixed = (toMove) % len(ar) 

ar = np.roll(ar,-oldPos) 
print(ar,'Roll to oldpos')

ar = np.delete(ar,0)
print(ar,'Delete first')

ar = np.roll(ar,-(toMoveFixed))
print(ar,'Roll to new pos')

ar = np.insert(ar,0,toMove)
print(ar,'Insert in front')

ar = np.roll(ar,toMoveFixed-1)
print(ar,'Roll back to old pos')

newPos = (oldPos+toMoveFixed)%len(ar)
print(newPos < oldPos)
ar = np.roll(ar,oldPos)
print(ar,'Roll back to original')

# if toMove > 0:

# else:


[ 4 -2  5  6  7  8  9] Start, move 6
[ 6  7  8  9  4 -2  5] Roll to oldpos
[ 7  8  9  4 -2  5] Delete first
[ 7  8  9  4 -2  5] Roll to new pos
[ 6  7  8  9  4 -2  5] Insert in front
[ 7  8  9  4 -2  5  6] Roll back to old pos
False
[-2  5  6  7  8  9  4] Roll back to original


7

In [348]:
ar = curIn.copy()
oldPos = 5

toMove = int(ar[oldPos])

print(ar,'Start, move',toMove)


if toMove > 0:
    toMoveFixed = (oldPos + toMove + 1) % len(ar)
else:
    toMoveFixed = (oldPos + toMove) % len(ar)

# print(toMoveFixed,oldPos)
if (toMoveFixed < oldPos):
    ar = np.delete(ar,oldPos)
    print(ar,'Delete')
else:
    ar = np.delete(ar,oldPos)
    print(ar,'Delete')

    
ar = np.insert(ar,toMoveFixed,toMove)
print(ar,'insert')


[ 4 -2  5  6  7  8  9] Start, move 8
[ 4 -2  5  6  7  9] Delete
[ 8  4 -2  5  6  7  9] insert


In [329]:
# Working solution, but the number should be popped before moving, otherwise it will be in the way for itself (and x > len(ar) will be one to small)
ar = curIn.copy()
oldPos = 4

print(ar,'Start')
toMove = int(ar[oldPos])

if toMove > 0:
    toMoveFixed = (oldPos + toMove + 1) % len(ar)
else:
    toMoveFixed = (oldPos + toMove) % len(ar)

ar = np.insert(ar,toMoveFixed,toMove)
print(ar,'insert')

if (toMoveFixed < oldPos):
    ar = np.delete(ar,oldPos+1)
    print(ar,'Delete')
else:
    ar = np.delete(ar,oldPos)
    print(ar,'Delete')

[ 1.  2. -3.  3. -2.  0.  4.] Start
[ 1.  2. -2. -3.  3. -2.  0.  4.] insert
[ 1.  2. -2. -3.  3.  0.  4.] Delete


In [284]:
ar = curIn.copy()
oldPos = 2

print(ar,'Start')
toMove = int(ar[oldPos])

ar = np.roll(ar,-oldPos)
print(ar,'To old pos')

if toMove > 0:
    ar = np.roll(ar,-toMove-1)
    print(ar,'To new pos, positive')
    ar = np.insert(ar,len(ar),toMove)
    print(ar,'Insert')
    
    ar = np.delete(ar,toMove-2)
    print(ar,'Pop original')

    ar = np.roll(ar,toMove+1)
    print(ar,'Roll back to old pos')

else:
    ar = np.roll(ar,-toMove)
    print(ar,'To new pos, negative')
    ar = np.insert(ar,len(ar),toMove)
    print(ar,'Insert')

    ar = np.delete(ar,-toMove)
    print(ar,'Pop original')

    ar = np.roll(ar,toMove)
    print(ar,'Roll back to old pos')






ar = np.roll(ar,oldPos)
print(ar,'Roll back to origial')



[ 4 -2  5  6  7  8  9] Start
[ 5  6  7  8  9  4 -2] To old pos
[-2  5  6  7  8  9  4] To new pos, positive
[-2  5  6  7  8  9  4  5] Insert
[-2  5  6  8  9  4  5] Pop original
[ 5  6  8  9  4  5 -2] Roll back to old pos
[ 5 -2  5  6  8  9  4] Roll back to origial


In [240]:
curAr = curIn.copy()
print(curAr,'Start')
oldPos = 1
oldPos = 3
toMove = int(curAr[oldPos])

print(toMove,'toMove')
np.roll(curAr,-toMove)
# newPos = ((oldPos+toMove-1)%len(curAr)) + 1
# # print((oldPos+toMove))
# curAr = np.insert(curAr,newPos,toMove)
# print(curAr,'Insert')
# curAr = np.delete(curAr,oldPos)
# print(curAr,'Delete')

[4 5 6 1 7 8 9] Start
1 toMove


array([5, 6, 1, 7, 8, 9, 4])

In [196]:
curAr = curIn.copy()
curOrd = np.arange(len(curIn))
oldPos = 3
toMove = int(curAr[oldPos])
newPos =((oldPos+toMove+1) % len(curIn)-1)
print(curAr,'Start')
# newPos =((oldPos+toMove) % len(curIn))
print(oldPos)
print(toMove) 
print(newPos)
# # print(((newPos+1) % len(curIn)-1))
# curAr =np.insert(curAr,newPos,toMove)
# print(curAr,'insert')
curAr =np.delete(curAr,oldPos)
print(curAr,'Delete old')
curAr =np.insert(curAr,newPos,toMove)
print(curAr,'insert')

[ 1.  2. -3.  3. -2.  0.  4.] Start
3
3
-1
[ 1.  2. -3. -2.  0.  4.] Delete old
[ 1.  2. -3. -2.  0.  3.  4.] insert


In [158]:
curAr = curIn.copy()
curOrd = np.arange(len(curIn))
oldPos = 0
toMove = int(curAr[oldPos])
print(curAr)
curAr = np.roll(curAr,-oldPos)
print(curAr,'Roll to front')
curAr = np.delete(curAr,0)
# curAr = np.delete(curAr,oldPos)
print(curAr,'Delete')
curAr = np.roll(curAr,-toMove)
print(curAr,'Roll to new pos')
curAr = np.append(curAr,toMove)
print(curAr,'Append')
curAr = np.roll(curAr,1)
print(curAr,'Roll to have appended in front')
curAr = np.roll(curAr,toMove+1)
print(curAr,'Roll back',toMove)
# # curAr = np.roll(curAr,oldPos)
# # curAr = np.roll(curAr,oldPos+toMove)
# # print(curAr,'Roll back to main configuration')

[ 1.  2. -3.  3. -2.  0.  4.]
[ 1.  2. -3.  3. -2.  0.  4.] Roll to front
[ 2. -3.  3. -2.  0.  4.] Delete
[-3.  3. -2.  0.  4.  2.] Roll to new pos
[-3.  3. -2.  0.  4.  2.  1.] Append
[ 1. -3.  3. -2.  0.  4.  2.] Roll to have appended in front
[ 4.  2.  1. -3.  3. -2.  0.] Roll back 1


In [85]:
curAr = curIn.copy()
curOrd = np.arange(len(curIn))

curPos = 0
# curInd = curOrd[curPos]
curInd = 0



print(curAr)

# while curInd < len(curIn):
for k in range(3):
    toMove = int(curAr[curPos])
    toMovePlace = toMove % (len(curAr)-1)

    print(toMove,'moves, or ',toMovePlace)


    curAr = np.delete(curAr,curPos)
    print('Delete:',curAr)

    curAr = np.roll(curAr,-curPos)
    print('Roll to position:',curAr)

    curAr = np.roll(curAr,-toMovePlace)
    print('Roll to new position:',curAr)

    curAr = np.append(curAr,toMove)
    print('Append:',curAr)

    curAr = np.roll(curAr ,toMovePlace+1)
    print('Roll back to new position:',curAr)

    curAr = np.roll(curAr,curPos)

    # Do the same with the order array
    curOrd = np.delete(curOrd,curPos)
    curOrd = np.append(np.roll(curOrd,-toMovePlace),curInd)
    curOrd = np.roll(curOrd ,toMovePlace+1)

    print(curAr)
    print(curOrd)

    # Get next
    nextInd = curInd + 1
    curPos = np.where(curOrd == nextInd)[0][0]
    curInd = curOrd[curPos]

    # toMove = int(curAr[curPos])
    # # if toMove 
    # toMove = toMove % len(curAr)

    # print('--')
    # curAr = np.delete(curAr,curPos)
    # curAr = np.append(np.roll(curAr,-toMove),toMove)
    # curAr = np.roll(curAr ,toMove+1)
    # # Do the same with the order array
    # curOrd = np.delete(curOrd,curPos)
    # curOrd = np.append(np.roll(curOrd,-toMove),curInd)
    # curOrd = np.roll(curOrd ,toMove+1)

    # print(curAr)
    # print(curOrd)

[ 1.  2. -3.  3. -2.  0.  4.]
1 moves, or  1
Delete: [ 2. -3.  3. -2.  0.  4.]
Roll to position: [ 2. -3.  3. -2.  0.  4.]
Roll to new position: [-3.  3. -2.  0.  4.  2.]
Append: [-3.  3. -2.  0.  4.  2.  1.]
Roll back to new position: [ 2.  1. -3.  3. -2.  0.  4.]
[ 2.  1. -3.  3. -2.  0.  4.]
[1 0 2 3 4 5 6]
2 moves, or  2
Delete: [ 1. -3.  3. -2.  0.  4.]
Roll to position: [ 1. -3.  3. -2.  0.  4.]
Roll to new position: [ 3. -2.  0.  4.  1. -3.]
Append: [ 3. -2.  0.  4.  1. -3.  2.]
Roll back to new position: [ 1. -3.  2.  3. -2.  0.  4.]
[ 1. -3.  2.  3. -2.  0.  4.]
[0 2 1 3 4 5 6]
-3 moves, or  3
Delete: [ 1.  2.  3. -2.  0.  4.]
Roll to position: [ 2.  3. -2.  0.  4.  1.]
Roll to new position: [ 0.  4.  1.  2.  3. -2.]
Append: [ 0.  4.  1.  2.  3. -2. -3.]
Roll back to new position: [ 2.  3. -2. -3.  0.  4.  1.]
[ 1.  2.  3. -2. -3.  0.  4.]
[0 1 3 2 4 5 6]
