In [5]:
# Import packages
import numpy as np
curDay = 9

# Download input file
from download_inputs import download_inputs

download_inputs(curDay)

200


In [6]:
# Load input into workspace
filename = f'inputs\\day{curDay}.txt'
# curIn = np.loadtxt(filename)

inputFile = open(filename)
inputs = []
inputs = [s for s in inputFile.read().splitlines()]

print('Done loading input')

Done loading input


In [10]:
# Load test-input into workspace
filenameTest = f'inputs\\day{curDay}test.txt'

inputFileTest = open(filenameTest)
inputsTest = []
inputsTest = [s for s in inputFileTest.read().splitlines()]

print('Done loading test-input')

Done loading test-input


# Part 1

array([0, 0])

In [78]:
curIn = inputsTest
curIn = inputs

startPos = np.array([0,0])

# Start with head movement
curHpos = startPos.copy()
curTpos = startPos.copy()

def getNewTpos(Tpos,Hpos,prevHpos):
    # Check if distance is too large
    diffX = Tpos[0] - Hpos[0]
    diffY = Tpos[1] - Hpos[1]
    toMove = False 
    if np.abs(diffX) > 1:
        toMove = True
    elif np.abs(diffY) > 1:
        toMove = True 
    
    # print(diffX,diffY)
    newTpos = Tpos.copy()
    if toMove:
        
        newTpos = prevHpos.copy()
        # # Figure out direction
        # if (diffY == 0):
        #     if diffX < 0:
        #         newTpos = Tpos + [1,0]
        #     else:
        #         newTpos = Tpos + [-1,0]
        # elif (diffX == 0):
        #     if diffY < 0:
        #         newTpos = Tpos + [0,1]
        #     else:
        #         newTpos = Tpos + [0,-1]
        # # If both are non-zero, move diagonally
        # elif (np.abs(diffX) > np.abs(diffY)):
        #     newTpos = Hpos.copy()


        # if np.abs(diffX) > np.abs(diffY):
        #     if diffX < 0:
        #         newTpos = Tpos + [1,0]
        #     else:
        #         newTpos = Tpos + [-1,0]
        # else:
        #     if diffY < 0:
        #         newTpos = Tpos + [0,1]
        #     else:
        #         newTpos = Tpos + [0,-1]

    return newTpos

allTpos = []
for m in curIn:
    curD,num = m.split(' ')
    num = int(num)

    for k in range(num):
        # print(curD)
        prevHpos = curHpos.copy()
        if (curD == 'R'):
            curHpos += [1,0]
        if (curD == 'U'):
            curHpos += [0,1]
        if (curD == 'D'):
            curHpos += [0,-1]
        if (curD == 'L'):
            curHpos += [-1,0]
        curTpos = getNewTpos(curTpos,curHpos,prevHpos)
        # print(curHpos,curTpos)
        allTpos.append(curTpos)

In [79]:
p1 = len(np.unique(allTpos,axis=0))
p1

6026

In [214]:
curIn = inputsTest
curIn = inputs

startPos = np.array([0,0])

# Start with head movement
curHpos = startPos.copy()
curTpos = startPos.copy()

def getNewTpos(Tpos,Hpos):
    # Check if distance is too large
    diffX = Tpos[0] - Hpos[0]
    diffY = Tpos[1] - Hpos[1]
    toMove = False 
    if np.abs(diffX) > 1:
        toMove = True
    elif np.abs(diffY) > 1:
        toMove = True 

        
    # if (diffX == 0) | (diffY == 0):
    #     newTpos = Tpos.copy()
    # else:
    #     if np.abs(diffX) > np.abs(diffY):

    # return newTpos
    
    # print(diffX,diffY)
    newTpos = Tpos.copy()
    if toMove:
        
        # newTpos = prevHpos.copy()
        # Figure out direction

        if (diffY == 0):
            if diffX < 0:
                newTpos = Tpos + [1,0]
            else:
                newTpos = Tpos + [-1,0]
        elif (diffX == 0):
            if diffY < 0:
                newTpos = Tpos + [0,1]
            else:
                newTpos = Tpos + [0,-1]
        # If both are non-zero, move diagonally
        else:
            newTpos = Tpos + [-np.sign(diffX),-np.sign(diffY)]
        # elif (np.abs(diffX) > np.abs(diffY)):
        #     newTpos = Hpos.copy()


        # if np.abs(diffX) > np.abs(diffY):
        #     if diffX < 0:
        #         newTpos = Tpos + [1,0]
        #     else:
        #         newTpos = Tpos + [-1,0]
        # else:
        #     if diffY < 0:
        #         newTpos = Tpos + [0,1]
        #     else:
        #         newTpos = Tpos + [0,-1]

    return newTpos

allTpos = []
for m in curIn:
    curD,num = m.split(' ')
    num = int(num)

    for k in range(num):
        # print(curD)
        prevHpos = curHpos.copy()
        if (curD == 'R'):
            curHpos += [1,0]
        if (curD == 'U'):
            curHpos += [0,1]
        if (curD == 'D'):
            curHpos += [0,-1]
        if (curD == 'L'):
            curHpos += [-1,0]
        curTpos = getNewTpos(curTpos,curHpos)
        # print(curHpos,curTpos)
        allTpos.append(curTpos)
p1 = len(np.unique(allTpos,axis=0))
p1

6026

In [80]:
# Load test-input into workspace
filenameTest2 = f'inputs\\day{curDay}test2.txt'

inputFileTest2 = open(filenameTest2)
inputsTest2 = []
inputsTest2 = [s for s in inputFileTest2.read().splitlines()]

print('Done loading test-input')

Done loading test-input


In [92]:
ropeParts = np.zeros((9,2))
ropeParts

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [251]:
curIn = inputsTest2
curIn = inputs

startPos = np.array([0,0])

# Start with head movement
curHpos = startPos.copy()
curTpos = startPos.copy()
ropeParts = np.zeros((9,2))


def getNewTpos(Tpos,Hpos):
    # Check if distance is too large
    diffX = Tpos[0] - Hpos[0]
    diffY = Tpos[1] - Hpos[1]
    toMove = False 
    if np.abs(diffX) > 1:
        toMove = True
    elif np.abs(diffY) > 1:
        toMove = True 
    
    newTpos = Tpos.copy()
    if toMove:
        
        # newTpos = prevHpos.copy()
        # Figure out direction

        if (diffY == 0):
            if diffX < 0:
                newTpos = Tpos + [1,0]
            else:
                newTpos = Tpos + [-1,0]
        elif (diffX == 0):
            if diffY < 0:
                newTpos = Tpos + [0,1]
            else:
                newTpos = Tpos + [0,-1]
        # If both are non-zero, move diagonally
        else:
            newTpos = Tpos + [-np.sign(diffX),-np.sign(diffY)]
    return newTpos

allTpos = []
for m in curIn:
# for m in curIn[:2]:
    # print(m)
    curD,num = m.split(' ')
    num = int(num)

    for k in range(num):
        prevHpos = curHpos.copy()
        if (curD == 'R'):
            curHpos += [1,0]
        if (curD == 'U'):
            curHpos += [0,1]
        if (curD == 'D'):
            curHpos += [0,-1]
        if (curD == 'L'):
            curHpos += [-1,0]

        curPrev = prevHpos 
        curMoveTo = curHpos 
        # print('H:' ,curPrev,curMoveTo)
        # print(curD,k)

        for p in range(9):
            curPpos = ropeParts[p]
            newPpos = getNewTpos(curPpos,curMoveTo)
            # print('-')
            # print(curPpos,'to',newPpos)
            # print('prev',curPrev)
            
            curMoveTo = curPpos.copy()
            if np.any(newPpos != curPpos):
                ropeParts[p] = newPpos 
                # curPrev = curPpos 
                curMoveTo = newPpos
            # print(curPrev,curMoveTo)
            # print(ropeParts)
        # curTpos = getNewTpos(curTpos,curHpos,prevHpos)
        # # print(curHpos,curTpos)
        # print(ropeParts[-1])
        # print(allTpos)
        # allTpos = np.vstack([allTpos,ropeParts[-1]])
        curTpos = ropeParts[-1].copy()
        # print(curTpos.shape)
        allTpos.append(curTpos)
        # print(allTpos.shape)
        # allTpos.append(ropeParts[-1].copy())
        
        # print(curHpos)
        # print(ropeParts)
    # print(curHpos)
    # print(ropeParts)
    
    # import matplotlib.pyplot as plt
    # fig,ax = plt.subplots()
    # ax.plot(curHpos[0],curHpos[1],'rs')
    # ax.plot(ropeParts[:,0],ropeParts[:,1],'b*')

    # ax.set_xlim([-16,16])
    # ax.set_ylim([-16,16])
# np.unique(allTpos,axis=0)

In [252]:
ropeParts

array([[153., -47.],
       [153., -48.],
       [153., -49.],
       [153., -50.],
       [153., -51.],
       [153., -52.],
       [153., -53.],
       [153., -54.],
       [153., -55.]])

In [253]:
allTpos= np.array(allTpos)

In [256]:
# import matplotlib.pyplot as plt 

# fig,ax = plt.subplots()
# # ax.plot(curHpos[0],curHpos[1],'rs')
# # ax.plot(ropeParts[:,0],ropeParts[:,1],'b*')
# ax.plot(allTpos[:,0],allTpos[:,1],'b*')

# ax.set_xlim([-12,12])
# ax.set_ylim([-16,16])
# # ax.set_xlim([-1,6])
# # ax.set_ylim([-1,6])



In [255]:
p2 = len(np.unique(allTpos,axis=0))
p2 

2273

In [223]:

p2 = len(np.unique(allTpos,axis=0))
p2

2527

In [143]:
allTpos

[array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.]),
 array([4., 0.])]